# Generated by Django 3.0.3 on 2020-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.TextField(default='Your blog post here'),
        ),
    ]
